name: Draft

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-unix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}

      - name: Build
        run: |
          cargo build --release --locked --target ${{ matrix.target }}

      - name: Pack artifact
        env:
          ARTIFACT_NAME: haze-${{ matrix.target }}
        run: |
          mkdir "$ARTIFACT_NAME"
          cp "target/${{ matrix.target }}/release/haze" "$ARTIFACT_NAME"
          cp README.md LICENSE "$ARTIFACT_NAME"
          if ! command -v zip &> /dev/null
          then
            sudo apt-get update && sudo apt-get install -yq zip
          fi
          zip -r "$ARTIFACT_NAME.zip" "$ARTIFACT_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: haze-${{ matrix.target }}.zip
          path: haze-${{ matrix.target }}.zip

  build-windows:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Pack artifact
        env:
          TARGET_NAME: haze-${{ matrix.target }}
        run: |
          New-Item -ItemType Directory -Path ${env:TARGET_NAME}
          Copy-Item -Path "target\${{ matrix.target }}\release\haze.exe" -Destination ${env:TARGET_NAME}
          Copy-Item -Path "README.md", "LICENSE" -Destination ${env:TARGET_NAME}
          Compress-Archive -Path ${env:TARGET_NAME} -DestinationPath "${env:TARGET_NAME}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: haze-${{ matrix.target }}.zip
          path: haze-${{ matrix.target }}.zip

  draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build-unix, build-windows]
    steps:
      - name: Grab artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: haze-*.zip
